services:
  graph:
    build:
      context: .
    ports:
      - "8000:8000"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      falkordb:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GRAPHITI_DB_TYPE=falkordb
      - FALKORDB_URL=redis://falkordb:6379
      - SEMAPHORE_LIMIT=20
      - PORT=8000

  falkordb:
    image: falkordb/falkordb:edge
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - falkordb_data:/data
    environment:
      - FALKOR_QUERY_TIMEOUT=300000
      - FALKOR_MAX_MEMORY=512MB
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"

volumes:
  falkordb_data:
